# -*- coding: utf-8 -*-
"""PulseAi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uelqxS0xH4ZKkEfhmbYH6SOB21UHGoMW

# IOT based Health Monitoring System using Different types of Machine Learning Algorithm.

# Package Importing
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""# Dataset Reading"""

Input_data = pd.read_csv("maternal_health_risk.csv")
Input_data

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.metrics import make_scorer, recall_score

# Drop unnecessary columns if they exist
if 'Patient ID' in Input_data.columns:
    Input_data = Input_data.drop('Patient ID', axis=1)

# Assuming the last column is the target
X = Input_data.iloc[:, :-1]
y = Input_data.iloc[:, -1]

# Handle categorical target variable
y = y.astype('category').cat.codes

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Apply SMOTE to the training data
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_scaled, y_train)

# Train a simple model
model = LogisticRegression()
model.fit(X_train_resampled, y_train_resampled)

# Make predictions and evaluate
y_pred = model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)

print("--- Logistic Regression ---")
print(f"Test Accuracy: {accuracy}")
print(classification_report(y_test, y_pred, target_names=['high', 'low', 'mid']))


models = {
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "Support Vector Machine": SVC(),
    "Gaussian Naive Bayes": GaussianNB(),
    "XGBoost": XGBClassifier()
}

for name, model in models.items():
    model.fit(X_train_resampled, y_train_resampled)
    y_pred = model.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"--- {name} ---")
    print(f"Test Accuracy: {accuracy}")
    print(classification_report(y_test, y_pred, target_names=['high', 'low', 'mid']))


print("\nTuning XGBoost for Recall...")
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.1, 0.01, 0.05]
}

# Define the scorer to optimize for recall on the 'high' risk class (encoded as 0)
recall_scorer = make_scorer(recall_score, pos_label=0)

xgb = XGBClassifier(eval_metric='mlogloss')
grid_search = GridSearchCV(estimator=xgb, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2, scoring=recall_scorer)
grid_search.fit(X_train_resampled, y_train_resampled)

print("Best parameters for recall: ", grid_search.best_params_)
best_xgb_recall = grid_search.best_estimator_
y_pred_best_recall = best_xgb_recall.predict(X_test_scaled)
print("\n--- Tuned XGBoost (Optimized for Recall) ---")
print(classification_report(y_test, y_pred_best_recall, target_names=['high', 'low', 'mid']))

